export const images = {
  onbordingimg1: require('./Onbordingimg1.png'),
  onbordingimg2: require('./Onbordingimg2.png'),
  onbordingimg3: require('./Onbordingimg3.png'),
  applogo: require('./Applogo.png'),
  hideicon: require('./Hideicon.png'),
  unhideicon: require('./Unhideicon.png'),
  accountimg: require('./Accountimg.png'),
  forgotimg: require('./Forgotimg.png'),
  passwordimg: require('./PasswordSuccessful.png'),
  home: require('./Home.png'),
  chat: require('./Message.png'),
  program: require('./Program.png'),
  profile: require('./Profile.png'),
  physioImg: require('./PhysioImg.png'),
};
