export const images = {
  onbordingimg1: require('./Onbordingimg1.png'),
  onbordingimg2: require('./Onbordingimg2.png'),
  onbordingimg3: require('./Onbordingimg3.png'),
  applogo: require('./Applogo.png'),
  hideicon: require('./Hideicon.png'),
  unhideicon: require('./Unhideicon.png'),
  forgotimg: require('./Forgotimg.png'),
  home: require('./Home.png'),
  chat: require('./Message.png'),
  program: require('./Program.png'),
  profile: require('./Profile.png'),
  physioImg: require('./PhysioImg.png'),
  clients: require('./Clients.png'),
  library: require('./Library.png'),
  squatImg1: require('./SquatImg1.png'),
  squatImg2: require('./SquatImg2.png'),
  squatImg3: require('./SquatImg3.png'),
  squatImg4: require('./SquatImg4.png'),
  squatImg5: require('./SquatImg5.png'),
};
